domain_path: /home/ishida/Documents/Kazan2/vitis/qsbi_boot/platform/zynqmp_fsbl/zynqmp_fsbl_bsp
app_src_dir: /tools/Xilinx/Vitis/2024.2/data/embeddedsw/lib/sw_apps/zynqmp_fsbl
template: zynqmp_fsbl
lang: c
